{{- if .Values.jupyterNotebook.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlrun-ce.jupyter.fullname" . }}
  labels:
    {{- include "mlrun-ce.jupyter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mlrun-ce.jupyter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlrun-ce.jupyter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.jupyterNotebook.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if  .Values.jupyterNotebook.serviceAccount.name }}
      serviceAccount: {{ .Values.jupyterNotebook.serviceAccount.name }}
{{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: jupyter-notebook
        image: "{{ .Values.jupyterNotebook.image.repository }}:{{ .Values.jupyterNotebook.image.tag }}"
        imagePullPolicy: {{ .Values.jupyterNotebook.image.pullPolicy }}
        env:
        - name: MLRUN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: MLRUN_DBPATH
          value: {{ printf "http://%s:%s" (include "mlrun-ce.mlrun.api.fullname" .) (include "mlrun-ce.mlrun.api.port" .) }}
        - name: MLRUN_UI_URL
          value: {{ template "mlrun-ce.jupyter.mlrunUIURL" . }}
        - name: MLRUN_MPIJOB_CRD_VERSION
          value: {{ index .Values "mpi-operator" "crd" "version" }}
{{- if  .Values.jupyterNotebook.persistence.enabled }}
        - name: MLRUN_PVC_MOUNT
          value: {{ printf "%s:/home/jovyan/" (include "mlrun-ce.jupyter.claimName" .) }}
{{- end }}
        - name: CHOWN_HOME
          value: "yes"
        - name: CHOWN_HOME_OPTS
          value: "-R"
        {{- if .Values.jupyterNotebook.extraEnv }}
        {{ toYaml .Values.jupyterNotebook.extraEnv | nindent 8 }}
        {{- end }}
        {{- if .Values.jupyterNotebook.extraEnvKeyValue }}
        {{- range $name, $value := .Values.jupyterNotebook.extraEnvKeyValue }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.jupyterNotebook.envFrom }}
        envFrom:
        {{ toYaml .Values.jupyterNotebook.envFrom | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /home/jovyan/
          name: notebooks
        ports:
        - containerPort: 8888
          name: http
        command: ["/bin/bash", "/usr/local/bin/mlce-start.sh"]
      {{- with .Values.jupyterNotebook.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jupyterNotebook.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: notebooks
        persistentVolumeClaim:
{{- if .Values.jupyterNotebook.persistence.enabled }}
          claimName: {{ template "mlrun-ce.jupyter.claimName" . }}
{{- end }}
{{- end -}}
